In [1]:
import pandas as pd

In [5]:
students = pd.read_csv('/Users/prathmeshsurwase/Desktop/Pandas & Numpy/groupby/students.csv')

In [6]:
students.head(5)

,student_id,name,age,city,course,marks,attendance,study_hours_per_week,placement_status,join_date
0,ST001,Aarav,18,Kolhapur,IT,78.0,62.0,16,Not Placed,2024-06-12
1,ST002,Diya,23,Mumbai,ENTC,44.0,98.0,29,Placed,2023-06-16
2,ST003,Ishaan,19,Pune,ENTC,43.0,68.0,14,Not Placed,2023-09-21
3,ST004,Meera,20,Pune,IT,NaN,92.0,29,Interviewing,2023-10-21
4,ST005,Kabir,20,Mumbai,Computer,47.0,68.0,26,Placed,2023-12-01

Count students in each course using groupby().

In [7]:
course = students.groupby('course')

In [9]:
course.size()

course
Civil          1
Computer       5
ENTC          11
IT             8
Mechanical     5
dtype: int64

In [15]:
students['course'].value_counts()

course
ENTC          11
IT             8
Computer       5
Mechanical     5
Civil          1
Name: count, dtype: int64

Find average marks by course.

In [16]:
course['marks'].mean()

course
Civil               NaN
Computer      71.250000
ENTC          67.636364
IT            64.714286
Mechanical    51.200000
Name: marks, dtype: float64

Find average attendance by city.

In [17]:
city = students.groupby('city')
city['attendance'].mean()

city
Aurangabad    84.000000
Kolhapur      74.166667
Mumbai        87.666667
Nagpur        72.400000
Nashik        59.000000
Pune          78.600000
Satara        88.000000
Solapur       63.000000
Name: attendance, dtype: float64

Find maximum marks by course.

In [20]:
course['marks'].max()

course
Civil          NaN
Computer      94.0
ENTC          97.0
IT            79.0
Mechanical    67.0
Name: marks, dtype: float64

Find minimum marks by course.

In [21]:
course['marks'].min()

course
Civil          NaN
Computer      47.0
ENTC          43.0
IT            42.0
Mechanical    42.0
Name: marks, dtype: float64

Calculate count, mean, median, minimum, and maximum marks by course using agg().

In [23]:
course['marks'].agg(['mean' , 'count' , 'min' , 'max' , 'median' ])

                 mean  count   min   max  median
course
Civil             NaN      0   NaN   NaN     NaN
Computer    71.250000      4  47.0  94.0    72.0
ENTC        67.636364     11  43.0  97.0    71.0
IT          64.714286      7  42.0  79.0    69.0
Mechanical  51.200000      5  42.0  67.0    44.0

Find the course with the highest average marks.

In [24]:
course['marks'].mean().sort_values(ascending=False).head(1)

course
Computer    71.25
Name: marks, dtype: float64

Find the city with the highest average attendance.

In [25]:
city['attendance'].mean().sort_values(ascending=False).head(1)

city
Satara    88.0
Name: attendance, dtype: float64

Find the top student in each course.

In [41]:
students.iloc[students.dropna(subset=['marks']).groupby('course')['marks'].idxmax()]

,student_id,name,age,city,course,marks,attendance,study_hours_per_week,placement_status,join_date
17,ST018,Sana,20,Satara,Computer,94.0,NaN,20,Not Placed,2023-08-20
6,ST007,Rohan,18,Kolhapur,ENTC,97.0,79.0,25,Not Placed,2024-05-26
12,ST013,Om,21,Aurangabad,IT,79.0,86.0,18,Not Placed,2023-10-05
10,ST011,Aditya,20,Nagpur,Mechanical,67.0,79.0,5,Not Placed,2024-07-25

In [46]:
course.apply(lambda x :x.nlargest(3,'marks'))

              student_id    name  age        city  marks  attendance  \
course
Civil      20      ST021   Arjun   18      Satara    NaN        88.0
Computer   17      ST018    Sana   20      Satara   94.0         NaN
           5       ST006   Anaya   22    Kolhapur   92.0         NaN
           14      ST015   Kunal   22  Aurangabad   52.0        63.0
ENTC       6       ST007   Rohan   18    Kolhapur   97.0        79.0
           13      ST014   Priya   22    Kolhapur   85.0        90.0
           24      ST025    Yash   20  Aurangabad   80.0        96.0
IT         12      ST013      Om   21  Aurangabad   79.0        86.0
           0       ST001   Aarav   18    Kolhapur   78.0        62.0
           19      ST020   Pooja   23      Nagpur   78.0        74.0
Mechanical 10      ST011  Aditya   20      Nagpur   67.0        79.0
           27      ST028    Riya   22      Nagpur   59.0        59.0
           8       ST009   Vivek   20         NaN   44.0        79.0

               study_hours_per_week placement_status   join_date
course
Civil      20                     3           Placed  2024-09-18
Computer   17                    20       Not Placed  2023-08-20
           5                     31           Placed  2024-10-11
           14                     5           Placed  2023-08-18
ENTC       6                     25       Not Placed  2024-05-26
           13                    29       Not Placed  2023-12-03
           24                    30           Placed  2023-10-05
IT         12                    18       Not Placed  2023-10-05
           0                     16       Not Placed  2024-06-12
           19                    25       Not Placed  2024-03-03
Mechanical 10                     5       Not Placed  2024-07-25
           27                    33       Not Placed  2024-03-03
           8                     12     Interviewing  2023-11-29

In [50]:
# Find students whose marks are above their course's average.

students.groupby('course', group_keys=False).apply(
    lambda x: x[x['marks'] > x['marks'].mean()]
)

,student_id,name,age,city,marks,attendance,study_hours_per_week,placement_status,join_date
5,ST006,Anaya,22,Kolhapur,92.0,NaN,31,Placed,2024-10-11
17,ST018,Sana,20,Satara,94.0,NaN,20,Not Placed,2023-08-20
6,ST007,Rohan,18,Kolhapur,97.0,79.0,25,Not Placed,2024-05-26
13,ST014,Priya,22,Kolhapur,85.0,90.0,29,Not Placed,2023-12-03
15,ST016,Ira,23,Solapur,78.0,65.0,6,Not Placed,2023-12-13
16,ST017,Rahul,22,Kolhapur,76.0,84.0,2,Placed,2024-05-15
23,ST024,Tara,21,Nagpur,71.0,93.0,14,Interviewing,2023-12-22
24,ST025,Yash,20,Aurangabad,80.0,96.0,30,Placed,2023-10-05
0,ST001,Aarav,18,Kolhapur,78.0,62.0,16,Not Placed,2024-06-12
12,ST013,Om,21,Aurangabad,79.0,86.0,18,Not Placed,2023-10-05
19,ST020,Pooja,23,Nagpur,78.0,74.0,25,Not Placed,2024-03-03
22,ST023,Neel,22,Nashik,69.0,59.0,32,Not Placed,2023-10-14
10,ST011,Aditya,20,Nagpur,67.0,79.0,5,Not Placed,2024-07-25
27,ST028,Riya,22,Nagpur,59.0,59.0,33,Not Placed,2024-03-03

In [51]:
studentss = students.dropna(subset=['marks'])

students[students['marks'] > course['marks'].transform('mean')]

,student_id,name,age,city,course,marks,attendance,study_hours_per_week,placement_status,join_date
0,ST001,Aarav,18,Kolhapur,IT,78.0,62.0,16,Not Placed,2024-06-12
5,ST006,Anaya,22,Kolhapur,Computer,92.0,NaN,31,Placed,2024-10-11
6,ST007,Rohan,18,Kolhapur,ENTC,97.0,79.0,25,Not Placed,2024-05-26
10,ST011,Aditya,20,Nagpur,Mechanical,67.0,79.0,5,Not Placed,2024-07-25
12,ST013,Om,21,Aurangabad,IT,79.0,86.0,18,Not Placed,2023-10-05
13,ST014,Priya,22,Kolhapur,ENTC,85.0,90.0,29,Not Placed,2023-12-03
15,ST016,Ira,23,Solapur,ENTC,78.0,65.0,6,Not Placed,2023-12-13
16,ST017,Rahul,22,Kolhapur,ENTC,76.0,84.0,2,Placed,2024-05-15
17,ST018,Sana,20,Satara,Computer,94.0,NaN,20,Not Placed,2023-08-20
19,ST020,Pooja,23,Nagpur,IT,78.0,74.0,25,Not Placed,2024-03-03
22,ST023,Neel,22,Nashik,IT,69.0,59.0,32,Not Placed,2023-10-14
23,ST024,Tara,21,Nagpur,ENTC,71.0,93.0,14,Interviewing,2023-12-22
24,ST025,Yash,20,Aurangabad,ENTC,80.0,96.0,30,Placed,2023-10-05
27,ST028,Riya,22,Nagpur,Mechanical,59.0,59.0,33,Not Placed,2024-03-03

Calculate each course's percentage of total students.

In [54]:
total =  course.size().sum()

In [55]:
print(total)

30

In [61]:
((course.size()/total )*100).round(2)

course
Civil          3.33
Computer      16.67
ENTC          36.67
IT            26.67
Mechanical    16.67
dtype: float64

Compare average marks by placement status.

In [63]:
placement = students.groupby('placement_status')

In [67]:
placement.size()

placement_status
Interviewing     4
Not Placed      16
Placed          10
dtype: int64

In [68]:
placement['marks'].mean()

placement_status
Interviewing    57.500000
Not Placed      66.375000
Placed          62.333333
Name: marks, dtype: float64

In [72]:
# Find courses with at least 5 students.
course.size() > 5

course
Civil         False
Computer      False
ENTC           True
IT             True
Mechanical    False
dtype: bool